[build]
  # Base directory containing the React app
  base = "client"
  
  # Build command for React app (running from client directory)
  command = "npm run build"
  
  # Directory with the built files (relative to base)
  publish = "build"
  
  # Environment variables for build
  [build.environment]
    REACT_APP_BASE_URL = "https://roomrento.onrender.com"
    REACT_APP_API_URL = "https://roomrento.onrender.com"
    REACT_APP_GOOGLE_MAPS_API_KEY = "AIzaSyADOYPe7t0IbbRuvzmNDbcYHOb98_cCTQk"
    REACT_APP_GOOGLE_CLIENT_ID = "632276644882-rnbq8prpeepluvtvpdqt0b0hie1rtr2b.apps.googleusercontent.com"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
