# Render deployment configuration for RoomRento API
services:
  - type: web
    name: roomrento-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: roomrento-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PORT
        value: 10000

databases:
  - name: roomrento-mongodb
    databaseName: roomrento
    user: roomrento_user
    plan: free
